controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"   # <- Humble 기준 정확한 이름
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "base_link"
    bt_loop_duration: 10
    navigators:
      - "navigate_to_pose"
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: "odom"
      robot_base_frame: "base_link"
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: "map"
      robot_base_frame: "base_link"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7
